name: CI 

on:
  push:
    branches: [ main ]

jobs:
  build_test:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Use OCaml 4.13.x
        uses: ocaml/setup-ocaml@v2
        with:
          ocaml-compiler: 4.13.x

      - name: Install Dependencies
        run: |
          opam install . --deps-only --with-test
          eval $(opam env)

      - name: Build Emulator
        run: make build

      - name: Run Unit Tests
        run: make test

  build_docs:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Use OCaml 4.13.x
        uses: ocaml/setup-ocaml@v2
        with:
          ocaml-compiler: 4.13.x

      - name: Install Dependencies
        run: |
          opam install . --deps-only --with-doc
          eval $(opam env)
      
      - name: Build Documentation
        run: |
          make docs
      
      - name: Copy documentation to gh-pages branch
        uses: actions/upload-artifact@v3
        with:
          name: docs
          path: docs
          retention-days: 1

  publish_docs:
    runs-on: ubuntu-latest
    needs: build_docs
    
    steps:
      - uses: actions/checkout@v2
        with:
          ref: gh-pages
      
      - name: Download documentation files
        uses: actions/download-artifact@v2
        with:
          name: docs
          path: docs
      
      - name: Commit
        uses: EndBug/add-and-commit@v9
        with:
          author_name: Charles Averill
          author_email: charlesaverill20@gmail.com
          message: "Latest docs - ${{ github.event.repository.updated_at}}"
          branch: gh-pages
          add: '[./*]'
